title: Maïwen Demeulle
description: Portfolio and research projects in Bioinformatics
baseurl: ""
url: "https://maideme.github.io"
github_username: MaiDeme
linkedin_username: maïwen-demeulle

theme: minima

header_pages:
  - about.md
  - projects.md
  - works.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:name/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - web_maiwen.zip
  - _site
